---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Christmas Capers
description:
original_url: https://codeclubprojects.org/en-GB/scratch/christmas-capers
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Make Rudolph fly
- title: Falling Presents
- title: Scoring and Sound Effects
- title: Game over
  completion: internal
- title: 'Challenge: Make the game harder'
